service: kaiju-refactor-rampage-site

frameworkVersion: "3"

plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}

custom:
  bucketName: ${self:service}-${self:provider.stage}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: ../dist/
    - bucketName: ${self:custom.bucketName}
      bucketPrefix: src/assets/images/
      localDir: ../src/assets/images/

resources:
  Resources:
    StaticSiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: false # Explicitly set to false to allow public policies
          IgnorePublicAcls: true
          RestrictPublicBuckets: false # Explicitly set to false to allow public policies

    StaticSiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref StaticSiteBucket
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource:
                - "arn:aws:s3:::${self:custom.bucketName}/*"
